CLAIM = "Anticoagulation should be resumed in this patient."

GOAL = "Prevent recurrent thromboembolic stroke."

PATIENT_FACTS = (
    "71M. Non-valvular atrial fibrillation; on apixaban 5\u202fmg BD for 3 years prior to admission. "
    "Spontaneous left thalamic intracerebral haemorrhage (ICH) 10 weeks ago. MRI susceptibility-weighted "
    "imaging shows >6 cortical microhaemorrhages, radiologically consistent with cerebral amyloid angiopathy (CAA) "
    "\u2014 a marker of substantially elevated re-bleed risk. "
    "Prior right MCA ischaemic stroke 2 years ago (residual mild dysphasia and right arm weakness). "
    "CHA\u2082DS\u2082-VASc score 6 (age \u226575, male, hypertension, prior stroke \u00d72, heart failure). "
    "HAS-BLED score 5 (hypertension, prior stroke, prior bleed, age >65, antiplatelet use). "
    "Heart failure with reduced ejection fraction (HFrEF, EF 32\u202f%), NYHA class II\u2013III; "
    "hospitalised for acute decompensation 6 weeks ago \u2014 elevates thromboembolic risk and complicates pharmacokinetics. "
    "Blood pressure: 152/94\u202fmmHg on triple antihypertensive therapy (ramipril 10\u202fmg, amlodipine 10\u202fmg, "
    "spironolactone 25\u202fmg) \u2014 persistently above target despite maximal tolerated doses; "
    "uncontrolled hypertension is a primary driver of both re-bleed and ischaemic stroke risk. "
    "eGFR 43\u202fmL/min/1.73m\u00b2 (CKD stage 3b, stable) \u2014 requires dose review for any resumed DOAC. "
    "Platelet count 118 \u00d7 10\u2079/L (mild thrombocytopenia of unknown cause); haematology review in progress \u2014 "
    "differential includes myelodysplastic syndrome, hepatic congestion, medication effect; bone marrow biopsy pending. "
    "Repeat CT head at 6 weeks: resolving haematoma, no mass effect, persistent microhaemorrhages. "
    "Current timing: 10 weeks post-ICH \u2014 below the 12-week minimum threshold recommended by neurology before reassessment. "
    "Neurology: advises against anticoagulation until at least 12 weeks post-ICH, with formal MDT review thereafter. "
    "Cardiology: strongly recommends early resumption given CHA\u2082DS\u2082-VASc 6 and HFrEF with low EF. "
    "Haematology: defer all antithrombotic therapy pending thrombocytopenia aetiology. "
    "Three-way specialist disagreement with no consensus recommendation documented. "
    "Patient: strongly prefers to restart anticoagulation, citing fear of another ischaemic stroke as primary concern. "
    "Family: opposed to resumption, citing re-bleed and CAA findings. "
    "Social: lives alone, no formal carer package; one unwitnessed mechanical fall 4 weeks ago. "
    "Current medications: ramipril, amlodipine, spironolactone, furosemide 40\u202fmg, aspirin 75\u202fmg "
    "(commenced post-ICH as interim bridge \u2014 itself a bleeding risk), atorvastatin 40\u202fmg, lansoprazole."
)
